### ISSUE TITLE
Error: make: *** [Makefile:57: install] Error 1

### ISSUE THREAD

**Issue by Haki-Malai** [tomasz-lisowski/swicc-drv-ifd#3]
Command: `sudo make install`
```bash
echo "\
FRIENDLYNAME \"swICC PC/SC IFD Driver v1.1.0\"\
\nDEVICENAME   /dev/null\
\nLIBPATH      /usr/lib/pcsc/drivers/serial/libswicc-drv-ifd.so.1.1.0"\
 > build/reader.conf
cp build/reader.conf /etc/reader.conf.d/libswicc-drv-ifd
cp: cannot create regular file '/etc/reader.conf.d/libswicc-drv-ifd': No such file or directory
make: *** [Makefile:57: install] Error 1
```

**Comment by tomasz-lisowski** [comment]
Seems like `/etc/reader.conf.d/` should exist due to https://man.archlinux.org/man/reader.conf.5.en, but please double-check that. I tested the build script on Ubuntu 21/22 and Debian 10/11 so perhaps for some odd reason the directory didn't exist on Arch? Otherwise, the `cp` binary on Arch is behaving a little weird, in which case you can copy the file manually and test if that works (`build/reader.conf` to `/etc/reader.conf.d/libswicc-drv-ifd`).

If you have any words of wisdom on how to avoid this issue in the future (on Arch), please let me know.

P.S. I am assuming you have installed all the dependencies (`pcscd` in particular).

**Comment by Haki-Malai** [comment]
Ok first **pcscd** needs the **ccid** package, found out while debugging pcscd with the `pcscd --foreground --debug` command
```bash
00000116 [140479557031936] hotplug_libudev.c:724:HPRegisterForHotplugEvents() No bundle files in pcsc drivers directory: /usr/lib/pcsc/drivers
```
To generate reader.conf.d files you need pcscd to be running using something like `pcscd --foreground --debug` and then run `sudo pcsc_scan` provides by the package **pcsc-tools**

Also pacman doesn't have **libpcsclite1** but [pcsclite](https://archlinux.org/packages/community/x86_64/pcsclite/)

**Comment by tomasz-lisowski** [comment]
Thanks for going through all this trouble! 

As for `ccid`, the `pcscd` package on Ubuntu/Debian has `libccid` as dependency but the driver itself (the `ccid` package) is only necessary for USB readers which `swicc-drv-ifd` is not. The error you're seeing is really just a warning indicating that there are no IFD drivers installed (no files inside `reader.conf.d`), which is normal. Think of each file in `reader.conf.d` as a driver for a card reader.

`reader.conf.d` can be just an empty directory, and it is created while installing the deps on Ubuntu/Debian. It seems like maybe it simply is not getting created while `pacman` installs `pcscd`.

**Comment by tomasz-lisowski** [comment]
Added a CI workflow to test multiple distros (640dc2c0fcf4814cd9243c86ac8b2feef311a412). Fixed some minor problems, but if you pull now, it should work flawlessly. The updated [/doc/install.md](https://github.com/tomasz-lisowski/swicc-drv-ifd/blob/master/doc/install.md) file also contains distro-specific steps. 
Here is the CI run on the latest commit: https://github.com/tomasz-lisowski/swicc-drv-ifd/actions/runs/3560691154

**Comment by Haki-Malai** [comment]
Awesome, thank you :heart:
