### ISSUE TITLE
swICC PC/SC Reader not reading any sim cards

### ISSUE THREAD

**Issue by DilipYadav03** [tomasz-lisowski/swicc-drv-ifd#5]
According to your guidelines mentioned in swSIM project, "The PC/SC interface allows it to connect to ANY phone with a SIM card slot"

I directly connected Android phones (Vivo A78 and Redmi A6) using USB cable, enabling USB debugging in the phones.

when I executed the following cmd from terminal 
sudo pcscd -f -d -T

src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0000 - 0x0007 (SWICC_NET_CLIENT_COUNT_MAX 8U)
src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0

once I run pcsc_scan from another terminal, I get the results as mentioned below
 
Reader 0: swICC PC/SC IFD Driver v1.2.0 00 00
Event number: 0
Card state: Card removed, 

I hope phone's settings needs to be changed or some drivers need to be installed. As you have mentioned, without using SIMTrace2, any other tool which forwards messages to and from the phone would work as well. 

Please suggest me what I should do to use swSIM project.

Thanks.

**Comment by tomasz-lisowski** [comment]
Could you please provide the full `pcscd` log?

**Comment by tomasz-lisowski** [comment]
I am also confused about your setup. What is connected to what and how?

**Comment by DilipYadav03** [comment]
> Could you please provide the full `pcscd` log?

src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0000
src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0
src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0001
src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0
.
.
.
src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0007
src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0

that is because 
#define SWICC_NET_CLIENT_COUNT_MAX 8U (Which means maximum 8 clients can be connected, as per my knowledge)


> I am also confused about your setup. What is connected to what and how?

my setup is very simple. 
1 Just installed swSIM and swicc-drv-ifd on my ubuntu machine.
2. Connected two Android phones (Vivo A78 and Redmi 6A) to ubuntu through USB cable, having enabled USB debugging in Android devices.
3. once I executed "sudo pcscd -f -d -T", pcsc daemon started waiting for card to connect.

I just wanted to cross check why there were no cards connected. So, I executed pcsc_scan from another terminal. The results were

Reader 0: swICC PC/SC IFD Driver v1.2.0 00 00
Event number: 0
Card state: Card removed,

Reader 1: swICC PC/SC IFD Driver v1.2.0 00 00
Event number: 0
Card state: Card removed,
.
.
.
Reader 7: swICC PC/SC IFD Driver v1.2.0 00 00
Event number: 0
Card state: Card removed,
/(were rotating) 

I understood that, pcsc_scan is waiting for card to connect.

**Comment by tomasz-lisowski** [comment]
**Regarding Bug**

What you're describing is not a bug and not unexpected behaviour. PC/SC polls each reader and while doing so, generates a log line `src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.` indicating that the reader it is polling at that instant is not minimal, i.e. the lowest index reader without a card inserted in it. Please double check the `pcscd` log because with no cards inserted, it must indicate `src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0000.` without the `not minimal` log after it because that is the lowest index reader like this:
```
00000110 [134259931088576] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0000.
00000161 [134259920602816] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0001.
00000020 [134259920602816] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00000114 [134259899631296] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0003.
00000040 [134259899631296] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00000060 [134259889145536] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0004.
00000014 [134259889145536] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00000052 [134259878659776] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0005.
00000017 [134259878659776] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00000151 [134259868174016] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0006.
00000026 [134259868174016] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00000023 [134259857688256] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0007.
00000017 [134259857688256] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
00399391 [134259910117056] src/ifd_handler.c:711:IFDHICCPresence() Lun=0x0002.
00000053 [134259910117056] src/ifd_handler.c:759:IFDHICCPresence() Slot empty but not minimal: min=0.
```
Notice how there are 7 indications the reader is not minimal, NOT 8.

**Regarding Your Setup**
I said:

>We used the [SIMtrace 2](https://osmocom.org/projects/simtrace2/wiki) device running on the [cardem firmware](https://osmocom.org/projects/simtrace2/wiki#card-emulation) but any other tool which forwards messages to and from the phone would work as well.

SIMtrace2 connects physically into your SIM card slot, and by saying "any other tool which forwards messages to and from the phone" I hoped it was pretty clear the physical connection to the SIM card slot was necessary. You cannot plug a SIM card into your Android phone only via ADB or similar, it requires that physical layer that sends SIM messages through the physical SIM interface.

**Why swSIM is not Detected**
It's not possible to "install" swSIM as the make file doesn't even have an `install` target. Instead you need to run it per the instructions on the swSIM repo. It will tell you if it can or can't connect to the virtual card readers, i.e., one of `swICC PC/SC IFD Driver v1.2.0 00 00`, but as long as you're running the generated `swsim.elf` binary, `pcsc_scan` will show that the reader is populated and it will also decode the ATR of swSIM.

**Comment by DilipYadav03** [comment]
Dear Tomasz,
I do agree, that your app doesn't have any bugs.
I'll check again and then let you know.
Thank you.
